version: '3.9'

volumes:
  dsl-parser-data:

services:
  dsl:
    image: ghcr.io/flickit-platform/flickit-dsl-parser:1.8.0
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - dsl-parser-data:/opt/dsl-parser
    environment:
      LANG: C.UTF-8
