name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  POSTGRES_USER: flickit
  POSTGRES_PASSWORD: flickit
  POSTGRES_DB: flickit
  DEFAULT_SCHEMA_NAME: assessment-core
  SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/flickit?currentSchema=assessment-core
  SPRING_DATASOURCE_USERNAME: flickit
  SPRING_DATASOURCE_PASSWORD: flickit

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Create Default Schema
        run: |
          psql -U ${{ env.POSTGRES_USER }} -c "CREATE SCHEMA ${{ env.DEFAULT_SCHEMA_NAME }};"
          psql -U ${{ env.POSTGRES_USER }} -c "SET search_path TO ${{ env.DEFAULT_SCHEMA_NAME }};"

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test
